services:
  _defaults:
    public:        true


##### Event Subscriber
  yipikai.firewall.event_subscriber:
    class:          Yipikai\FirewallBundle\EventSubscriber\FirewallEventSubscriber
    tags:
      - { name: kernel.event_subscriber }

##### Firewall Listener
  yipikai.firewall.listener:
    class:          Yipikai\FirewallBundle\Listener\FirewallListener
    arguments:      ["@kernel", "@yipikai.firewall", "@yipikai.firewall.config", "@?event_dispatcher"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: execute, priority: 30 }

##### Configuration
  yipikai.firewall.config:
    class:          Yipikai\FirewallBundle\Configuration\FirewallConfiguration
    arguments:      [ "%yipikai_firewall%" ]

##### Firewall
  yipikai.firewall:
    class:          Yipikai\FirewallBundle\Services\Firewall
    arguments:      [ "@yipikai.firewall.config" ]