services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true


##### Event Subscriber
  ipikai\FirewallBundle\EventSubscriber\FirewallEventSubscriber:
    tags:
      - { name: kernel.event_subscriber }
  yipikai.firewall.event_subscriber:
    alias:          Yipikai\FirewallBundle\EventSubscriber\FirewallEventSubscriber

##### Firewall Listener
  Yipikai\FirewallBundle\Listener\FirewallListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: execute, priority: 30 }
  yipikai.firewall.listener:
    alias:          Yipikai\FirewallBundle\Listener\FirewallListener

##### Configuration
  Yipikai\FirewallBundle\Configuration\FirewallConfiguration: ~
  yipikai.firewall.config:
    alias:          Yipikai\FirewallBundle\Configuration\FirewallConfiguration

##### Firewall
  Yipikai\FirewallBundle\Services\Firewall: ~
  yipikai.firewall:
    alias:          Yipikai\FirewallBundle\Services\Firewall